type Task {
  _id: ID!
  title: String!
  description: String!
  isImportant: Boolean!
  owner: User!
  created_at: Date!
  updated_at: Date
}

input TaskInput {
  title: String!
  description: String!
  isImportant: Boolean!
  owner: ID!
}

type Query {
  tasks: [Task]!
}

type Mutation {
  createTask(data: TaskInput): Task!
  updateTask(id: ID!, data: TaskInput): Task!
  deleteTask(id: ID!): Boolean!
}